### ISSUE TITLE
Display sparkline default value should be 'false'

### ISSUE THREAD

**Issue by Heizelmann** [saxn-paule/pimatic-datetime#1]

**Comment by Heizelmann** [comment]
Should be false for all numeric attributes

**Comment by Heizelmann** [comment]
Further all attributes should be listed in the xAttributeOptions list weather they are default or not.

**Comment by saxn-paule** [comment]
@Heizelmann Sparklines are hidden by default now. Please test.

**Comment by Heizelmann** [comment]
Unfortunately, it still doesn't work.

**Comment by saxn-paule** [comment]
What exactly does not work? Please create a new device. All sparklines should be hidden by default.

**Comment by Heizelmann** [comment]
I set all sparkline to default of my existing device. Now it looks like
```
{
      "name": "datetime",
      "class": "DateTimeDevice",
      "xAttributeOptions": [
        {
          "name": "dayOfWeek"
        },
        {
          "name": "dayOfMonth"
        },
        {
          "name": "dayOfYear"
        },
        {
          "name": "week"
        },
        {
          "name": "weekend"
        },
        {
          "name": "time"
        },
        {
          "name": "date"
        },
        {
          "name": "datetime"
        },
        {
          "name": "formatted"
        },
        {
          "name": "unixTimestamp"
        }
      ],
      "id": "datetime",
      "locale": "de-DE",
      "dateformat": "dddd DD.MM.YYYY HH:mm:ss",
      "interval": 1000
    }
```

Updated plugin, restarted Pimatic, and also restarted browser. Still all sparklines are visible.

**Comment by saxn-paule** [comment]
> Please create a **new** device. All sparklines should be hidden by default. 

Or delete all xAttributeOptions once. Then displaySparklines will be **set to false** initially. I cannot change the global default behavior of pimatic! So this is the only way to go.

The moment you add xAttributeOptions by your own, it doesn't work any longer for the corresponding attribute. Make your own changes afterwards.

**Comment by Heizelmann** [comment]
I think you don'nt need the sparkline feature at all for this kind of device. More important is 'label' and 'hidden' May be you can take SunriseDevice as an example, there it works as desired.

**Comment by saxn-paule** [comment]
The sparkline feature is active **by pimatic default** for all numeric variables. You need to deactivate it explicitly.
The SunriseDevice isn't numeric, so there is not sparkline at all.

**Comment by saxn-paule** [comment]
Added possibility to add a label for attributes. Published in v0.2.0
https://github.com/saxn-paule/pimatic-datetime/commit/19ad1eea48a1c766db63c436101e91317b7cfca1
https://github.com/saxn-paule/pimatic-datetime/tree/v0.2.0

**Comment by Heizelmann** [comment]
Thanks for the explanation, then probably it is an issue for the Pimatic core software. 

May be one short refinement can be done: In the device editor the list of xAttributes offered initially is not complete. I had to add weekend, time, date and datetime manually.

Great plugin!

**Comment by saxn-paule** [comment]
All **numeric** values are added to the xAttributeOptions. The variables you mentioned aren't numeric. So there is no need to disable sparklines for them.

**Comment by Heizelmann** [comment]
And what about the 'hidden' attribute?

**Comment by saxn-paule** [comment]
Your request was to **hide sparklines for numeric values**. Thats done.
All other changes could be done by your own. Whether via GUI or via config.js

It doesn't make any sense to add all attributes to the xAttributeOptions by default. That bloats the config.js unnecessarily.

As the original request is solved, I will close this.
